sudo: required # 관리자 권한을 받기 위해 

language: generic 

services: 
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t smilejenny/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true smilejenny/docker-react-app npm run test -- --coverage

# after_sucess:
#   - echo "Test success"

# git 에 push한후 travis에서 확인

deploy: 
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-467416368414"
  bakcet_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

# url: https://467416368414.signin.aws.amazon.com/console
# name: jenny
# pw: ctA1_L|1