FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install 

COPY ./ ./

CMD ["npm", "run", "start"]

# 빌드 : docker build -f Dockerfile.dev -t jenny/docker-react .
# 볼륨을 이용한 실행 : docker run -it -p 3000:3000 -v /usr/src/app/node_modules -v $(pwd):/usr/src/app jenny/docker-react